# Generated by Django 4.1.1 on 2024-04-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_debitnote_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.purchasebill'),
        ),
    ]
