# Generated by Django 4.1.1 on 2024-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_remove_debitnote_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='created_at',
            field=models.DateField(),
        ),
    ]
