# Generated by Django 4.1.1 on 2024-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_alter_debitnote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
