# Generated by Django 4.1.1 on 2024-05-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_alter_debitnote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.purchasebill'),
        ),
    ]
