# Generated by Django 4.1.1 on 2024-05-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_debitnote_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='party',
            new_name='partye',
        ),
    ]
