# Generated by Django 4.1.1 on 2024-05-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_rename_party_debitnote_partye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='partye',
            new_name='party',
        ),
    ]
