# Generated by Django 4.1.1 on 2024-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_rename_partye_debitnote_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='bill',
            new_name='purchasebill',
        ),
    ]
