# Generated by Django 4.1.1 on 2024-05-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_rename_bill_debitnote_purchasebill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='purchasebill',
        ),
    ]
