# Generated by Django 4.1.1 on 2024-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0014_remove_debitnote_purchasebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='grandtotal',
            field=models.FloatField(default=0, null=True),
        ),
    ]
