# Generated by Django 4.1.1 on 2024-05-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0015_alter_debitnote_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
